### ISSUE TITLE
Deploy to production the latest OrgBook BC Code

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-configurations#105]
Please prepare a release of OrgBook BC and push it to production.    This is mostly done as the latest code is on Dev and Test.  Things that I'm not aware are done:

1. Tag Aries VCR with a release tag for what is being deployed, so that we have visibility into what has changed since the last deployment (OCP 4 launch).
2. Likewise, tag the OrgBook BC Client.  This is the first release, so we won't be able to see what's changed, although some of it was done in both AVCR and OrgBook BC Client, so we should have some visibility.
3. Decide with the team on a deployment date, so I can notify those interested.

Please provide enough time between the tagging and the deployment so I can get a notification out.

Thanks

@WadeBarnes @amanji @ianco @CharlesMacpherson

**Comment by WadeBarnes** [comment]
The initial release of the [bcgov/orgbook-bc-client](https://github.com/bcgov/orgbook-bc-client) was just completed.  The PR for removing the client code from [bcgov/aries-vcr](https://github.com/bcgov/aries-vcr) id here; [Client extraction](https://github.com/bcgov/aries-vcr/pull/672)

I'll generate the tags/release once we're certain what revision of code is going to `prod`.

**Comment by swcurran** [comment]
@amanji @ianco -- Please let Wade know what code is going to prod.  He's waiting on that, per above.

**Comment by WadeBarnes** [comment]
I'm hoping for latest of both [bcgov/aries-vcr](https://github.com/bcgov/aries-vcr) and [bcgov/orgbook-bc-client](https://github.com/bcgov/orgbook-bc-client) once we get the [Client extraction](https://github.com/bcgov/aries-vcr/pull/672) PR merged.  That way we have all our significant project reorg/refactor out of the way.

**Comment by WadeBarnes** [comment]
@amanji, Is this release going to require a Solr re-indexing?

**Comment by amanji** [comment]
There shouldn't be a reindex required. The `main` branch for both repos should have the latest changes that are in production. There is a branch that is relevant for the Issuer Agency called `issuer-agency` which will add support for some 2.0 protocol handling but that will likely get merged a bit later.

**Comment by WadeBarnes** [comment]
@ianco, @amanji, and I had a quick meeting to review the changes between `prod` and the latest code.  We've confirmed none of the changes will require a re-indexing, and there are no issues that need to be addressed before release to `prod`.  I'm going to deploy the latest code to `test` for a smoke test.

**Comment by WadeBarnes** [comment]
@swcurran, @ianco and @amanji have smoke tested everything in the `test` environment.  As for release tags, are you happy with  `1.7.0` for [bcgov/aries-vcr](https://github.com/bcgov/aries-vcr), and `1.0.0` for [bcgov/orgbook-bc-client](https://github.com/bcgov/orgbook-bc-client)?  Additionally we can release anytime.  Would the morning of 2021.06.03 (this Thursday) give you enough time to notify everyone?

**Comment by swcurran** [comment]
That sounds good.  To confirm -- everything since 0.6.0 in Aries VCR is going to be added -- 83 commits.  Is that right?

**Comment by WadeBarnes** [comment]
> That sounds good. To confirm -- everything since 0.6.0 in Aries VCR is going to be added -- 83 commits. Is that right?

Everything since the [Aries VCR 1.6.0](https://github.com/bcgov/aries-vcr/releases/1.6.0) release, which is what is currently in `prod`.

**Comment by WadeBarnes** [comment]
@amanji, @ianco, Could you add details on any additional relevant changes to these release notes please:
- [Aries VCR 1.7.0](https://github.com/bcgov/aries-vcr/releases/1.7.0)
- [OrgBook Client 1.0.0](https://github.com/bcgov/orgbook-bc-client/releases/1.0.0)

**Comment by amanji** [comment]
Looks like @swcurran covered the major changes in his email notification.

* Removes display of multiple instances of the same legal name in autocomplete results. 
* A new "fuzzy search" has been added to allow organizations to experiment with data cleanups using OrgBook data. Apps that have been collecting typed in data for the legal name of an entity may be able to use the API to automate the clean up of their data.
* Fixed a bug related to indexing a credential for the first time.
* Extracted the BC client (user interface) code into a separate repo - aries-vcr-client.
* Cleanups to the "get help" email and to the get help guidance.
* Update the Aries Agent in Aries VCR to the latest 0.6.0 release of ACA-Py, and related changes, including updating to the V2.0 Credential Exchange protocols.
* Updated documentation on Aries VCR and guidance on creating a user interface using an Aries VCR backend.
* Routine security hygiene, including updating dependencies with known security vulnerabilities.
* Improvements to running Aries VCR in a development environment.
