### ISSUE TITLE
Please update the email addresses for OrgBook queries

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-configurations#107]
Please change the email addresses for notifications from the OrgBook form from Ian Armstrong to Dwayne Gordon (dwayne.gordon@gov.bc.ca).

Assigning to Wade, but redirect as needed.

Thanks

**Comment by WadeBarnes** [comment]
@swcurran, Done.  Test email sent.  Awaiting confirmation before closing.

**Comment by DJ-Gordon** [comment]
Confirmed receipt of the test email.
