### ISSUE TITLE
Deploy OrgBook v2 to Production

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-configurations#112]
Checklist:
- [x]  Ensure BC Registries Agent is ready to go to production. - @WadeBarnes 
  - The differences between the code in `test` and `prod` only impacts the local development environments.
- [x] Update `orgbook-bc-client-vue` (OrgBook V2) - @wadeking98, @amanji 
  - [x] Update to display all schema attributes as highlighted by default, thus eliminating the need for issuers to update their schemas right away.
  - [x] Add icons; https://github.com/bcgov/orgbook-bc-client-vue/issues/35, https://github.com/bcgov/orgbook-bc-client-vue/pull/66, https://github.com/bcgov/orgbook-bc-client-vue/pull/68
  - [x] Fix autocomplete dropdown display issue; https://github.com/bcgov/orgbook-bc-client-vue/pull/71. - @amanji 
  - [x] Fix issues:
    - [x] https://github.com/bcgov/orgbook-bc-client-vue/issues/69
    - [x] https://github.com/bcgov/orgbook-bc-client-vue/issues/72
    - [x] https://github.com/bcgov/orgbook-bc-client-vue/issues/75
    - [x] https://github.com/bcgov/orgbook-bc-client-vue/issues/78
    - [x] https://github.com/bcgov/orgbook-bc-client-vue/issues/77
      - Mitigated
    - [x] https://github.com/bcgov/orgbook-bc-client-vue/issues/85
    - [x] https://github.com/bcgov/orgbook-bc-client-vue/issues/84
    - [x] https://github.com/bcgov/orgbook-bc-client-vue/issues/91
    - [x] https://github.com/bcgov/orgbook-bc-client-vue/issues/86
- [x] Update `aries-vcr` - @wadeking98 
  - [x] Fix small migration issue; https://github.com/bcgov/aries-vcr/pull/720
  - [x] Complete and merge https://github.com/bcgov/aries-vcr/pull/711
- [x] Test new issuer registration protocols in `aries-vcr` with an older version of an issuer. - @ianco 
  - No issues found.
- [x] Deploy to `test` for final testing - @WadeBarnes 
  - Some minor UI issues discovered.
- [x] Inform issuer partners of the optional schema updates they can make.  Provide links to docs and examples. - @swcurran, @ianco
- [x] Deploy to `prod` for final testing - @WadeBarnes 
- [x] Schedule and announce the switchover to our clients and partners. - @swcurran 
- [x] Cut releases
  - [x] [bcgov/aries-vcr](https://github.com/bcgov/aries-vcr)
  - [x] [bcgov/orgbook-bc-client](https://github.com/bcgov/orgbook-bc-client)
  - [x] [bcgov/orgbook-bc-client-vue](https://github.com/bcgov/orgbook-bc-client-vue)
- [x] Switch `https://[*.]orgbook.gov.bc.ca/` urls to OrgBook v2 UI. - @WadeBarnes 
  - [x] Edit the `frontend-bc` routes.  Point them at the `frontend-v2-bc` service.  This allows things to be switched back if needed.
- [x] Decommission and clean-up OrgBook v1 UI and associated resources and CI/CD processes once the migration is deemed stable. - @WadeBarnes 
  - [x] Deploy the migrated configurations in the [feature/OrgBookv2](https://github.com/bcgov/orgbook-configurations/tree/feature/OrgBookv2) branch.
  - [x] Run the [orgBookV2Cleanup](https://github.com/bcgov/orgbook-configurations/blob/feature/OrgBookv2/openshift/manage#L1181) script.
  - [x] Merge the `feature/OrgBookv2` branch.

**Current State**

`prod`:
BC Reg Agent - `30e10648e6516664663f6a810bcbad3486ddf3c8`
OrgBook (`aries-vcr`) - `b12cae92426fd00d6a43c37ea5a18822899098ba`
OrgBook (`orgbook-bc-client`) - `0406e459a7c626b306ead381e8382a6fa96033bf`
OrgBook (`orgbook-bc-client-vue`) - `72454881ef1852ef7624da3a9bd6988b361df23f`

`test`:
BC Reg Agent - `30e10648e6516664663f6a810bcbad3486ddf3c8`
OrgBook (`aries-vcr`) - `b12cae92426fd00d6a43c37ea5a18822899098ba`
OrgBook (`orgbook-bc-client`) - `0406e459a7c626b306ead381e8382a6fa96033bf`
OrgBook (`orgbook-bc-client-vue`) - `72454881ef1852ef7624da3a9bd6988b361df23f`

`dev`:
BC Reg Agent - `30e10648e6516664663f6a810bcbad3486ddf3c8`
OrgBook (`aries-vcr`) - `b12cae92426fd00d6a43c37ea5a18822899098ba`
OrgBook (`orgbook-bc-client`) - `0406e459a7c626b306ead381e8382a6fa96033bf`
OrgBook (`orgbook-bc-client-vue`) - `72454881ef1852ef7624da3a9bd6988b361df23f`

`latest`:
BC Reg Agent - `30e10648e6516664663f6a810bcbad3486ddf3c8`
OrgBook (`aries-vcr`) - `b12cae92426fd00d6a43c37ea5a18822899098ba`
OrgBook (`orgbook-bc-client`) - `0406e459a7c626b306ead381e8382a6fa96033bf`
OrgBook (`orgbook-bc-client-vue`) - `72454881ef1852ef7624da3a9bd6988b361df23f`

OrgBook (`orgbook-bc-client-vue`) is dependent on OrgBook (`aries-vcr`) `19ce67547d5fc7ad0097f22cba3aa397f4c070d2` or newer.

**Comment by swcurran** [comment]
Over to you @WadeBarnes to run the final steps and close this issue.

**Comment by WadeBarnes** [comment]
Complete
