### ISSUE TITLE
Deploy OrgBook BC "test" code to prod

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-configurations#114]
AFAIK -- this is only a front end deployment. I've tested the features on test and am good with them going to production. More changes are needed, but they can go in a subsequent update.

Please let me know if the changes are to other than the frontend.

Thanks

**Comment by WadeBarnes** [comment]
**prod**
- aries-vcr: `62ba94fd3761d9b1bd3c90a8ea30f477133449d0`
- orgbook-bc-client: `62ba94fd3761d9b1bd3c90a8ea30f477133449d0`

**test**
- aries-vcr: `c4580f57502ac99e7d47d231383b88bf775f1d03`
- orgbook-bc-client: `c4580f57502ac99e7d47d231383b88bf775f1d03`

**dev**
- aries-vcr: `c4580f57502ac99e7d47d231383b88bf775f1d03`
- orgbook-bc-client: `c4580f57502ac99e7d47d231383b88bf775f1d03`

**Comment by WadeBarnes** [comment]
[bcgov/aries-vcr v1.9.2](https://github.com/bcgov/aries-vcr/releases/1.9.2) and [bcgov/orgbook-bc-client v1.0.4](https://github.com/bcgov/orgbook-bc-client/releases/v1.0.4) have been deployed to `prod`; https://orgbook.gov.bc.ca
